### ISSUE TITLE
dead?

### ISSUE THREAD

**Issue by darkzbaron** [victorloux/fb-scraper#1]
Getting Oops, something unexpected happened. Page title: Facebook ÔÇô log in or sign up when launching

**Comment by patniharshit** [comment]
Hi @darkzbaron, my pull request #2  fixes this issue.

**Comment by victorloux** [comment]
Thanks a lot @patniharshit this is now merged.

I am not maintaining this project (the code is almost 4 years old and I will have expected the Facebook code to change), but happy to accept other PRs if this is still useful for more people.
